# Define a porta do servidor Java (Usa a porta do Render ou 8080 localmente)
server.port=${PORT:8080}

# Configuração do Banco de Dados em Memória (H2)
spring.datasource.url=jdbc:h2:mem:cinestackdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Permite aceder ao painel do banco de dados no navegador (util para testes locais)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Dialeto e criação de tabelas
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# 'create' garante que o banco é limpo e o import.sql é executado a cada início
spring.jpa.hibernate.ddl-auto=create

# Configurações para garantir a execução do import.sql
spring.sql.init.mode=always
# MUITO IMPORTANTE: Aguarda as tabelas serem criadas para rodar o SQL de inserção
spring.jpa.defer-datasource-initialization=true

# Mostrar o SQL no console (bom para debug no Render se algo falhar)
spring.jpa.show-sql=true